class SuraDM {
  final String suraNameAr;
  final String suraNameEn;
  final String verses;
  final int index;

  SuraDM({
    required this.index,
    required this.suraNameAr,
    required this.suraNameEn,
    required this.verses,
  });
}

class ConstantsManager {
  static List<SuraDM> quranSuras = [
    SuraDM(
      index: 1,
      suraNameAr: "الفاتحه",
      suraNameEn: "Al-Fatiha",
      verses: "7",
    ),
    SuraDM(
      index: 2,
      suraNameAr: "البقرة",
      suraNameEn: "Al-Baqarah",
      verses: "286",
    ),
    SuraDM(
      index: 3,
      suraNameAr: "آل عمران",
      suraNameEn: "Aal-E-Imran",
      verses: "200",
    ),
    SuraDM(
      index: 4,
      suraNameAr: "النساء",
      suraNameEn: "An-Nisa'",
      verses: "176",
    ),
    SuraDM(
      index: 5,
      suraNameAr: "المائدة",
      suraNameEn: "Al-Ma'idah",
      verses: "120",
    ),
    SuraDM(
      index: 6,
      suraNameAr: "الأنعام",
      suraNameEn: "Al-An'am",
      verses: "165",
    ),
    SuraDM(
      index: 7,
      suraNameAr: "الأعراف",
      suraNameEn: "Al-A'raf",
      verses: "206",
    ),
    SuraDM(
      index: 8,
      suraNameAr: "الأنفال",
      suraNameEn: "Al-Anfal",
      verses: "75",
    ),
    SuraDM(
      index: 9,
      suraNameAr: "التوبة",
      suraNameEn: "At-Tawbah",
      verses: "129",
    ),
    SuraDM(index: 10, suraNameAr: "يونس", suraNameEn: "Yunus", verses: "109"),
    SuraDM(index: 11, suraNameAr: "هود", suraNameEn: "Hud", verses: "123"),
    SuraDM(index: 12, suraNameAr: "يوسف", suraNameEn: "Yusuf", verses: "111"),
    SuraDM(index: 13, suraNameAr: "الرعد", suraNameEn: "Ar-Ra'd", verses: "43"),
    SuraDM(
      index: 14,
      suraNameAr: "إبراهيم",
      suraNameEn: "Ibrahim",
      verses: "52",
    ),
    SuraDM(index: 15, suraNameAr: "الحجر", suraNameEn: "Al-Hijr", verses: "99"),
    SuraDM(
      index: 16,
      suraNameAr: "النحل",
      suraNameEn: "An-Nahl",
      verses: "128",
    ),
    SuraDM(
      index: 17,
      suraNameAr: "الإسراء",
      suraNameEn: "Al-Isra",
      verses: "111",
    ),
    SuraDM(
      index: 18,
      suraNameAr: "الكهف",
      suraNameEn: "Al-Kahf",
      verses: "110",
    ),
    SuraDM(index: 19, suraNameAr: "مريم", suraNameEn: "Maryam", verses: "98"),
    SuraDM(index: 20, suraNameAr: "طه", suraNameEn: "Ta-Ha", verses: "135"),
    SuraDM(
      index: 21,
      suraNameAr: "الأنبياء",
      suraNameEn: "Al-Anbiya",
      verses: "112",
    ),
    SuraDM(index: 22, suraNameAr: "الحج", suraNameEn: "Al-Hajj", verses: "78"),
    SuraDM(
      index: 23,
      suraNameAr: "المؤمنون",
      suraNameEn: "Al-Mu'minun",
      verses: "118",
    ),
    SuraDM(index: 24, suraNameAr: "النّور", suraNameEn: "An-Nur", verses: "64"),
    SuraDM(
      index: 25,
      suraNameAr: "الفرقان",
      suraNameEn: "Al-Furqan",
      verses: "77",
    ),
    SuraDM(
      index: 26,
      suraNameAr: "الشعراء",
      suraNameEn: "Ash-Shu'ara",
      verses: "227",
    ),
    SuraDM(
      index: 27,
      suraNameAr: "النّمل",
      suraNameEn: "An-Naml",
      verses: "93",
    ),
    SuraDM(
      index: 28,
      suraNameAr: "القصص",
      suraNameEn: "Al-Qasas",
      verses: "88",
    ),
    SuraDM(
      index: 29,
      suraNameAr: "العنكبوت",
      suraNameEn: "Al-Ankabut",
      verses: "69",
    ),
    SuraDM(index: 30, suraNameAr: "الرّوم", suraNameEn: "Ar-Rum", verses: "60"),
    SuraDM(index: 31, suraNameAr: "لقمان", suraNameEn: "Luqman", verses: "34"),
    SuraDM(
      index: 32,
      suraNameAr: "السجدة",
      suraNameEn: "As-Sajda",
      verses: "30",
    ),
    SuraDM(
      index: 33,
      suraNameAr: "الأحزاب",
      suraNameEn: "Al-Ahzab",
      verses: "73",
    ),
    SuraDM(index: 34, suraNameAr: "سبأ", suraNameEn: "Saba", verses: "54"),
    SuraDM(index: 35, suraNameAr: "فاطر", suraNameEn: "Fatir", verses: "45"),
    SuraDM(index: 36, suraNameAr: "يس", suraNameEn: "Ya-Sin", verses: "83"),
    SuraDM(
      index: 37,
      suraNameAr: "الصافات",
      suraNameEn: "As-Saffat",
      verses: "182",
    ),
    SuraDM(index: 38, suraNameAr: "ص", suraNameEn: "Sad", verses: "88"),
    SuraDM(
      index: 39,
      suraNameAr: "الزمر",
      suraNameEn: "Az-Zumar",
      verses: "75",
    ),
    SuraDM(index: 40, suraNameAr: "غافر", suraNameEn: "Ghafir", verses: "85"),
    SuraDM(
      index: 41,
      suraNameAr: "فصّلت",
      suraNameEn: "Fussilat",
      verses: "54",
    ),
    SuraDM(
      index: 42,
      suraNameAr: "الشورى",
      suraNameEn: "Ash-Shura",
      verses: "53",
    ),
    SuraDM(
      index: 43,
      suraNameAr: "الزخرف",
      suraNameEn: "Az-Zukhruf",
      verses: "89",
    ),
    SuraDM(
      index: 44,
      suraNameAr: "الدّخان",
      suraNameEn: "Ad-Dukhan",
      verses: "59",
    ),
    SuraDM(
      index: 45,
      suraNameAr: "الجاثية",
      suraNameEn: "Al-Jathiya",
      verses: "37",
    ),
    SuraDM(
      index: 46,
      suraNameAr: "الأحقاف",
      suraNameEn: "Al-Ahqaf",
      verses: "35",
    ),
    SuraDM(index: 47, suraNameAr: "محمد", suraNameEn: "Muhammad", verses: "38"),
    SuraDM(index: 48, suraNameAr: "الفتح", suraNameEn: "Al-Fath", verses: "29"),
    SuraDM(
      index: 49,
      suraNameAr: "الحجرات",
      suraNameEn: "Al-Hujurat",
      verses: "18",
    ),
    SuraDM(index: 50, suraNameAr: "ق", suraNameEn: "Qaf", verses: "45"),
    SuraDM(
      index: 51,
      suraNameAr: "الذاريات",
      suraNameEn: "Adh-Dhariyat",
      verses: "60",
    ),
    SuraDM(index: 52, suraNameAr: "الطور", suraNameEn: "At-Tur", verses: "49"),
    SuraDM(index: 53, suraNameAr: "النجم", suraNameEn: "An-Najm", verses: "62"),
    SuraDM(
      index: 54,
      suraNameAr: "القمر",
      suraNameEn: "Al-Qamar",
      verses: "55",
    ),
    SuraDM(
      index: 55,
      suraNameAr: "الرحمن",
      suraNameEn: "Ar-Rahman",
      verses: "78",
    ),
    SuraDM(
      index: 56,
      suraNameAr: "الواقعة",
      suraNameEn: "Al-Waqi'a",
      verses: "96",
    ),
    SuraDM(
      index: 57,
      suraNameAr: "الحديد",
      suraNameEn: "Al-Hadid",
      verses: "29",
    ),
    SuraDM(
      index: 58,
      suraNameAr: "المجادلة",
      suraNameEn: "Al-Mujadila",
      verses: "22",
    ),
    SuraDM(
      index: 59,
      suraNameAr: "الحشر",
      suraNameEn: "Al-Hashr",
      verses: "24",
    ),
    SuraDM(
      index: 60,
      suraNameAr: "الممتحنة",
      suraNameEn: "Al-Mumtahina",
      verses: "13",
    ),
    SuraDM(index: 61, suraNameAr: "الصف", suraNameEn: "As-Saff", verses: "14"),
    SuraDM(
      index: 62,
      suraNameAr: "الجمعة",
      suraNameEn: "Al-Jumu'a",
      verses: "11",
    ),
    SuraDM(
      index: 63,
      suraNameAr: "المنافقون",
      suraNameEn: "Al-Munafiqun",
      verses: "11",
    ),
    SuraDM(
      index: 64,
      suraNameAr: "التغابن",
      suraNameEn: "At-Taghabun",
      verses: "18",
    ),
    SuraDM(
      index: 65,
      suraNameAr: "الطلاق",
      suraNameEn: "At-Talaq",
      verses: "12",
    ),
    SuraDM(
      index: 66,
      suraNameAr: "التحريم",
      suraNameEn: "At-Tahrim",
      verses: "12",
    ),
    SuraDM(index: 67, suraNameAr: "الملك", suraNameEn: "Al-Mulk", verses: "30"),
    SuraDM(
      index: 68,
      suraNameAr: "القلم",
      suraNameEn: "Al-Qalam",
      verses: "52",
    ),
    SuraDM(
      index: 69,
      suraNameAr: "الحاقة",
      suraNameEn: "Al-Haqqah",
      verses: "52",
    ),
    SuraDM(
      index: 70,
      suraNameAr: "المعارج",
      suraNameEn: "Al-Ma'arij",
      verses: "44",
    ),
    SuraDM(index: 71, suraNameAr: "نوح", suraNameEn: "Nuh", verses: "28"),
    SuraDM(index: 72, suraNameAr: "الجن", suraNameEn: "Al-Jinn", verses: "28"),
    SuraDM(
      index: 73,
      suraNameAr: "المزّمّل",
      suraNameEn: "Al-Muzzammil",
      verses: "20",
    ),
    SuraDM(
      index: 74,
      suraNameAr: "المدّثر",
      suraNameEn: "Al-Muddathir",
      verses: "56",
    ),
    SuraDM(
      index: 75,
      suraNameAr: "القيامة",
      suraNameEn: "Al-Qiyamah",
      verses: "40",
    ),
    SuraDM(
      index: 76,
      suraNameAr: "الإنسان",
      suraNameEn: "Al-Insan",
      verses: "31",
    ),
    SuraDM(
      index: 77,
      suraNameAr: "المرسلات",
      suraNameEn: "Al-Mursalat",
      verses: "50",
    ),
    SuraDM(
      index: 78,
      suraNameAr: "النبأ",
      suraNameEn: "An-Naba'",
      verses: "40",
    ),
    SuraDM(
      index: 79,
      suraNameAr: "النازعات",
      suraNameEn: "An-Nazi'at",
      verses: "46",
    ),
    SuraDM(index: 80, suraNameAr: "عبس", suraNameEn: "Abasa", verses: "42"),
    SuraDM(
      index: 81,
      suraNameAr: "التكوير",
      suraNameEn: "At-Takwir",
      verses: "29",
    ),
    SuraDM(
      index: 82,
      suraNameAr: "الإنفطار",
      suraNameEn: "Al-Infitar",
      verses: "19",
    ),
    SuraDM(
      index: 83,
      suraNameAr: "المطفّفين",
      suraNameEn: "Al-Mutaffifin",
      verses: "36",
    ),
    SuraDM(
      index: 84,
      suraNameAr: "الإنشقاق",
      suraNameEn: "Al-Inshiqaq",
      verses: "25",
    ),
    SuraDM(
      index: 85,
      suraNameAr: "البروج",
      suraNameEn: "Al-Buruj",
      verses: "22",
    ),
    SuraDM(
      index: 86,
      suraNameAr: "الطارق",
      suraNameEn: "At-Tariq",
      verses: "17",
    ),
    SuraDM(
      index: 87,
      suraNameAr: "الأعلى",
      suraNameEn: "Al-A'la",
      verses: "19",
    ),
    SuraDM(
      index: 88,
      suraNameAr: "الغاشية",
      suraNameEn: "Al-Ghashiyah",
      verses: "26",
    ),
    SuraDM(index: 89, suraNameAr: "الفجر", suraNameEn: "Al-Fajr", verses: "30"),
    SuraDM(
      index: 90,
      suraNameAr: "البلد",
      suraNameEn: "Al-Balad",
      verses: "20",
    ),
    SuraDM(
      index: 91,
      suraNameAr: "الشمس",
      suraNameEn: "Ash-Shams",
      verses: "15",
    ),
    SuraDM(index: 92, suraNameAr: "الليل", suraNameEn: "Al-Lail", verses: "21"),
    SuraDM(index: 93, suraNameAr: "الضحى", suraNameEn: "Ad-Duha", verses: "11"),
    SuraDM(
      index: 94,
      suraNameAr: "الشرح",
      suraNameEn: "Ash-Sharh",
      verses: "8",
    ),
    SuraDM(index: 95, suraNameAr: "التين", suraNameEn: "At-Tin", verses: "8"),
    SuraDM(index: 96, suraNameAr: "العلق", suraNameEn: "Al-Alaq", verses: "19"),
    SuraDM(index: 97, suraNameAr: "القدر", suraNameEn: "Al-Qadr", verses: "5"),
    SuraDM(
      index: 98,
      suraNameAr: "البينة",
      suraNameEn: "Al-Bayyina",
      verses: "8",
    ),
    SuraDM(
      index: 99,
      suraNameAr: "الزلزلة",
      suraNameEn: "Az-Zalzalah",
      verses: "8",
    ),
    SuraDM(
      index: 100,
      suraNameAr: "العاديات",
      suraNameEn: "Al-Adiyat",
      verses: "11",
    ),
    SuraDM(
      index: 101,
      suraNameAr: "القارعة",
      suraNameEn: "Al-Qari'a",
      verses: "11",
    ),
    SuraDM(
      index: 102,
      suraNameAr: "التكاثر",
      suraNameEn: "At-Takathur",
      verses: "8",
    ),
    SuraDM(index: 103, suraNameAr: "العصر", suraNameEn: "Al-Asr", verses: "3"),
    SuraDM(
      index: 104,
      suraNameAr: "الهمزة",
      suraNameEn: "Al-Humazah",
      verses: "9",
    ),
    SuraDM(index: 105, suraNameAr: "الفيل", suraNameEn: "Al-Fil", verses: "5"),
    SuraDM(index: 106, suraNameAr: "قريش", suraNameEn: "Quraysh", verses: "4"),
    SuraDM(
      index: 107,
      suraNameAr: "الماعون",
      suraNameEn: "Al-Ma'un",
      verses: "7",
    ),
    SuraDM(
      index: 108,
      suraNameAr: "الكوثر",
      suraNameEn: "Al-Kawthar",
      verses: "3",
    ),
    SuraDM(
      index: 109,
      suraNameAr: "الكافرون",
      suraNameEn: "Al-Kafirun",
      verses: "6",
    ),
    SuraDM(index: 110, suraNameAr: "النصر", suraNameEn: "An-Nasr", verses: "3"),
    SuraDM(
      index: 111,
      suraNameAr: "المسد",
      suraNameEn: "Al-Masad",
      verses: "5",
    ),
    SuraDM(
      index: 112,
      suraNameAr: "الإخلاص",
      suraNameEn: "Al-Ikhlas",
      verses: "4",
    ),
    SuraDM(
      index: 113,
      suraNameAr: "الفلق",
      suraNameEn: "Al-Falaq",
      verses: "5",
    ),
    SuraDM(index: 114, suraNameAr: "الناس", suraNameEn: "An-Nas", verses: "6"),
  ];
}
